/**
 * SPDX-FileCopyrightText: Copyright 2022 - 2023 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.tsddr.tsddrbl.util.enums;

public enum ParametroAcaris {

	ANNOTAZIONE(1L),
	ANNOTAZIONE_FORMALE(2L),
	AOO_PROTOCOLLANTE(3L),
	AOO_RESPONSABILE_DELLA_MATERIA(4L),
	APPLICA_ANNOTAZIONE_A_CLASSIFICAZIONE_CORRENTE(5L),
	APPLICA_ANNOTAZIONE_A_INTERO_DOCUMENTO(6L),
	APPLICATIVO_ALIMENTANTE(7L),
	ARCHIVIO_CORRENTE(8L),
	AUTENTICATO(9L),
	AUTENTICATO_CON_FIRMA_AUTENTICA(10L),
	AUTENTICATO_COPIA_AUTENTICA(11L),
	CARTACEO(12L),
	COMPOSIZIONE(13L),
	CONSENTI_CREAZIONE_FASCICOLI(14L),
	CONSENTI_INSERIMENTO_DOCUMENTI(15L),
	CONSENTI_RICLASSIFICAZIONE_DOCUMENTI_NEL_DOSSIER(16L),
	CONSENTI_RICLASSIFICAZIONE_FASCICOLI_NEL_DOSSIER(17L),
	CONSERVAZIONE_CORRENTE(18L),
	CONSERVAZIONE_GENERALE(19L),
	COPIA_CARTACEA(20L),
	DESTINATARI_INTERNI(21L),
	DESTINATARIO_GIURIDICO(22L),
	FORMA_DOCUMENTARIA_TIPOLOGIA_DOCUMENTALE(23L),
	GRADO_DI_VITALITA(24L),
	MOLTEPLICITA_DELLA_COMPOSIZIONE(25L),
	NODO_PROTOCOLLANTE(16L),
	NODO_RESPONSABILE_DELLA_MATERIA(27L),
	ORIGINE_INTERNA(28L),
	PRESENZA_FILE(29L),
	PROTOCOLLISTA(30L),
	REGISTRAZIONE_RISERVATA(31L),
	RIMANDA_SBUSTAMENTO(32L),
	STATO_DEFINITIVO(33L),
	STATO_DI_EFFICACIA(34L),
	STATO_MODIFICABILE(35L),
	STATO_REGISTRATO(36L),
	STRUTTURA_PROTOCOLLANTE(37L),
	STRUTTURA_RESPONSABILE_DELLA_MATERIA(38L),
	TIPO(39L),
	TIPO_DOCUMENTO(40L),
	TIPOLOGIA(41L),
	TIPOLOGIA_DATI_PERSONALI(42L),
	TIPOLOGIA_DATI_RISERVATI(43L),
	TIPOLOGIA_DATI_SENSIBILI(44L),
	UTENTE_DI_CREAZIONE(45L),
	VITAL_RECORD_CODE(46L);
		
    private Long id;

    private ParametroAcaris(Long id) {
        this.id = id;
    }

    /**
     * @return the id
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(Long id) {
        this.id = id;
    }
    
}
