export * from './dichiarazione-tab-annotazioni/dichiarazione-tab-annotazioni.component';
export * from './dichiarazione-tab-rifiuti/dichiarazione-tab-rifiuti.component';
export * from './dichiarazione-tab-versamenti/dichiarazione-tab-versamenti.component';
export * from './dichiarazione-tab-annotazioni/dichiarazione-tab-annotazioni.component';
export * from './dichiarazione-tabs/dichiarazione-tabs.component';
export * from './dichiarazione-tab-sede/dichiarazione-tab-sede.component';
export * from './dichiarazione-tab-soggetti/dichiarazione-tab-soggetti.component';
export * from './popup-dichiarazione-exist/popup-dichiarazione-exist.component';
export * from './confirm-save/confirm-save.component';